version: '3'
services:
  myapp:
    tty: true
    ports:
     - "6669:6669"
     - "6670:22"
    build: .
    volumes:
      - .:/app
    networks:
      network:
        ipv4_address: 172.18.0.10